app/reports/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField
from wtforms.validators import DataRequired
from wtforms.fields.html5 import DateField
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from app.models import Department


def get_departments():
    return Department.query.all()


class WorkShiftReportsForm(FlaskForm):
    start_date = DateField(
        'Начало периода',
        format='%Y-%m-%d',
        validators=[DataRequired()],
    )
    end_date = DateField(
        'Окончание периода',
        format='%Y-%m-%d',
        validators=[DataRequired()],
    )
    department = QuerySelectField(
        'Подразделение',
        validators=[DataRequired()],
        query_factory=get_departments,
    )
    submit = SubmitField('Сформировать')


class WorkShiftReportsDownloadForm(FlaskForm):
    submit = SubmitField('Скачать')

app/reports/__init__.py
from flask import Blueprint

bp = Blueprint('reports', __name__)

from app.reports import views

app/reports/views.py
import os
from uuid import uuid4

from flask import render_template, flash, send_file, current_app, abort
from flask_login import login_required

from app.reports import bp
from app.models import (
    create_shift_report,
    Category,
    Employees,
    WorkShift,
    csv_to_xlsx,
)
from app.reports.forms import WorkShiftReportsForm


@bp.route('/reports', methods=['GET', 'POST'])
@login_required
def create_reports():
    reports = WorkShiftReportsForm()
    filename = uuid4()

    if reports.validate_on_submit():

        employees = (
            WorkShift.query.filter(
                WorkShift.start_date >= reports.start_date.data,
                WorkShift.end_date <= reports.end_date.data,
                Employees.department == reports.department.data,
            ).outerjoin(Employees).all()
        )

        create_shift_report(employees=employees, filename=filename)
        csv_to_xlsx(filename=filename)

        flash('Отчет сформирован', Category.SUCCESS.title)

    return render_template(
        'reports/reports.html',
        filename=filename,
        reports=reports,
    )


@bp.route('/uploads/<path:filename>', methods=['GET', 'POST'])
@login_required
def download(filename):
    try:
        return send_file(
            os.path.join(
                current_app.config['CSV_UPLOADS_DIRECTORY'],
                f'{filename}.xlsx',
            ),
            attachment_filename=f'{filename}.xlsx',
            mimetype='application/'
                     'vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            as_attachment=True,
        )
    except FileNotFoundError:
        abort(404)

app/templates/reports/reports.html
{% extends "layout.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<hr>
<h3 align="center">Формирование отчета</h3>
<hr>
{% block app_content %}

<form class="container" action="" method="post" role="form" novalidate>
    {{ reports.hidden_tag() }}
    <div class="row">
        <div class="col">
            {{wtf.form_field(reports.start_date)}}
        </div>
        <div class="col">
            {{wtf.form_field(reports.end_date)}}
        </div>
        <div class="col">
            {{wtf.form_field(reports.department)}}
        </div>
    </div>
    <hr>
    <div class="row" align="center">
        <div class="col">
            {{ wtf.form_field(reports.submit, class="btn btn-dark")}}
        </div>
        <div class="col">
            <a class="btn btn-success"
               href="{{ url_for('reports.download', filename=filename) }}">Выгрузить
                отчет</a>
        </div>
    </div>

</form>

{% endblock %}

{% endblock %}